/**
 * blogdata.js — Single source of truth for all blog categories and posts.
 * Imported by: app/articles/page.js, components/blog/CategoryPage.jsx, components/blog/BlogCard.jsx
 */

export const IMAGE_PLACEHOLDER_ICON = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8.5" cy="8.5" r="1.5"/><path d="M21 15l-5-5L5 21"/></svg>`;

export const CATEGORIES = [
  {
    slug: "strength_trainig",
    label: "Strength Training",
    shortLabel: "Strength",
    description: "Progressive overload, structural mechanics, and evidence-based programming for building real strength.",
    accentColor: "#c8a96e",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M6.5 6.5l11 11M6.5 17.5l11-11M12 2v4M12 18v4M2 12h4M18 12h4"/></svg>`,
  },
  {
    slug: "cardio_&_endurance",
    label: "Cardio & Endurance",
    shortLabel: "Cardio",
    description: "VO2 max, work capacity, and sustainable protocols for aerobic performance that lasts.",
    accentColor: "#6ea8c8",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/><path d="M3 12h4l2-3 4 6 2-3h4"/></svg>`,
  },
  {
    slug: "yoga_&_mobility",
    label: "Yoga & Mobility",
    shortLabel: "Mobility",
    description: "Joint health, flexibility science, and movement quality for athletes who want to last.",
    accentColor: "#8ec88a",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="5" r="2"/><path d="M12 7v5M8 20l2-7M16 20l-2-7M9 12h6"/></svg>`,
  },
  {
    slug: "home_workouts",
    label: "Home Workouts",
    shortLabel: "Home",
    description: "No gym, no excuses. Equipment-minimal and bodyweight training built for real consistency.",
    accentColor: "#c8906e",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9,22 9,12 15,12 15,22"/></svg>`,
  },
  {
    slug: "recovery_&_wellness",
    label: "Recovery & Wellness",
    shortLabel: "Recovery",
    description: "Sleep, nutrition timing, and the adaptation science that turns hard training into real gains.",
    accentColor: "#a86ec8",
    icon: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 12a9 9 0 0 1-9 9m9-9a9 9 0 0 0-9-9m9 9H3m9 9a9 9 0 0 1-9-9m9 9c1.66 0 3-4.03 3-9s-1.34-9-3-9m0 18c-1.66 0-3-4.03-3-9s1.34-9 3-9"/></svg>`,
  },
];

export const BLOG_DATA = {
  "strength_trainig": {
    featured: {
      id: "forge",
      slug: "forge",
      category: "Strength Training",
      tag: "FEATURED",
      readTime: "10 min",
      title: "Forge: Building Strength from First Principles",
      excerpt: "A return to the fundamentals — why progressive overload, tension, and recovery are all you need.",
      image: "https://qvqrllepiterihelgckb.supabase.co/storage/v1/object/public/Assets/Articles/strength_trainig/forge.webp",
    },
    posts: [
      {
        id: "raw_power",
        slug: "raw_power",
        category: "Strength Training",
        tag: "POWER",
        readTime: "8 min",
        title: "Raw Power: Developing Explosive Strength",
        excerpt: "The distinction between strength and power, and how to train both effectively.",
      },
      {
        id: "structural_edge",
        slug: "structural_edge",
        category: "Strength Training",
        tag: "SCIENCE",
        readTime: "8 min",
        title: "Structural Edge: Anatomy, Leverage, and Training Smarter",
        excerpt: "How your body structure affects exercise selection and where to focus your energy.",
      },
      {
        id: "iron_core",
        slug: "iron_core",
        category: "Strength Training",
        tag: "CORE",
        readTime: "7 min",
        title: "Iron Core: Building a Foundation of Functional Strength",
        excerpt: "Core training beyond crunches — how true trunk stability transfers to every lift.",
      },
      {
        id: "strength_protocol",
        slug: "strength_protocol",
        category: "Strength Training",
        tag: "PROTOCOL",
        readTime: "12 min",
        title: "Strength Protocol: Designing Training That Actually Works",
        excerpt: "From rep ranges to rest periods — the variables that separate effective programming from guesswork.",
      },
    ],
  },

  "cardio_&_endurance": {
    featured: {
      id: "engine_room",
      slug: "engine_room",
      category: "Cardio & Endurance",
      tag: "SCIENCE",
      readTime: "10 min",
      title: "Inside the Engine Room: VO2 Max and Cardiac Output",
      excerpt: "Understanding the physiological machinery that powers elite aerobic performance.",
      image: "https://qvqrllepiterihelgckb.supabase.co/storage/v1/object/public/Assets/Articles/cardio_&_endurance/inside_the_engine_room.webp",
    },
    posts: [
      {
        id: "endurance_edge",
        slug: "endurance_edge",
        category: "Cardio & Endurance",
        tag: "STRATEGY",
        readTime: "6 min",
        title: "Find Your Endurance Edge",
        excerpt: "Science-backed strategies to push past perceived limits and sustain effort longer.",
      },
      {
        id: "stamina_lab",
        slug: "stamina_lab",
        category: "Cardio & Endurance",
        tag: "TRAINING",
        readTime: "8 min",
        title: "The Stamina Lab: Building Work Capacity That Lasts",
        excerpt: "Methodical training protocols designed to expand your endurance ceiling week by week.",
      },
      {
        id: "aerobic_forge",
        slug: "aerobic_forge",
        category: "Cardio & Endurance",
        tag: "ENDURANCE",
        readTime: "7 min",
        title: "Build Your Aerobic Base from the Ground Up",
        excerpt: "How progressive cardio training reshapes your cardiovascular system for lasting endurance.",
      },
      {
        id: "distance_protocol",
        slug: "distance_protocol",
        category: "Cardio & Endurance",
        tag: "PROTOCOL",
        readTime: "9 min",
        title: "The Distance Protocol: Training for Long-Form Endurance",
        excerpt: "A structured approach to building mileage and stamina for distance events.",
      },
    ],
  },

  "yoga_&_mobility": {
    featured: {
      id: "mobility_lab",
      slug: "mobility_lab",
      category: "Yoga & Mobility",
      tag: "MOBILITY",
      readTime: "9 min",
      title: "Mobility Lab: Systematic Protocols for Every Major Joint",
      excerpt: "Hip, shoulder, thoracic, and ankle mobility — a comprehensive, evidence-based guide.",
      image: "https://qvqrllepiterihelgckb.supabase.co/storage/v1/object/public/Assets/Articles/yoga_&_mobility/mobility_lab.webp",
    },
    posts: [
      {
        id: "flex_protocol",
        slug: "flex_protocol",
        category: "Yoga & Mobility",
        tag: "FLEXIBILITY",
        readTime: "6 min",
        title: "Flex Protocol: A Science-Based Approach to Flexibility",
        excerpt: "Stretching, PNF, and loaded mobility — what the evidence says about getting more flexible.",
      },
      {
        id: "joint_intelligence",
        slug: "joint_intelligence",
        category: "Yoga & Mobility",
        tag: "JOINTS",
        readTime: "8 min",
        title: "Joint Intelligence: Training Healthy, Resilient Joints",
        excerpt: "Why joint health is the foundation of longevity in training — and how to build it.",
      },
      {
        id: "flow_state",
        slug: "flow_state",
        category: "Yoga & Mobility",
        tag: "YOGA",
        readTime: "7 min",
        title: "Flow State: Using Yoga to Enhance Athletic Performance",
        excerpt: "How a consistent yoga practice builds movement quality and body awareness serious athletes need.",
      },
      {
        id: "movement_mastery",
        slug: "movement_mastery",
        category: "Yoga & Mobility",
        tag: "MASTERY",
        readTime: "7 min",
        title: "Movement Mastery: From Stiffness to Fluidity",
        excerpt: "A progressive system for reclaiming full range of motion and moving pain-free.",
      },
    ],
  },

  "home_workouts": {
    featured: {
      id: "home_ground",
      slug: "home_ground",
      category: "Home Workouts",
      tag: "FEATURED",
      readTime: "8 min",
      title: "Home Ground: Making Your Space Your Gym",
      excerpt: "How to set up, structure and stay consistent with home-based training.",
      image: "https://qvqrllepiterihelgckb.supabase.co/storage/v1/object/public/Assets/Articles/home_workouts/home_ground.webp",
    },
    posts: [
      {
        id: "minimal_forge",
        slug: "minimal_forge",
        category: "Home Workouts",
        tag: "MINIMAL",
        readTime: "7 min",
        title: "Minimal Forge: Maximum Results with Minimum Equipment",
        excerpt: "Resistance bands, a pull-up bar, and a floor — here is everything you need.",
      },
      {
        id: "anywhere_strong",
        slug: "anywhere_strong",
        category: "Home Workouts",
        tag: "BODYWEIGHT",
        readTime: "6 min",
        title: "Anywhere Strong: Train Without Equipment",
        excerpt: "A complete guide to building real strength with nothing but your bodyweight and floor space.",
      },
      {
        id: "space_protocol",
        slug: "space_protocol",
        category: "Home Workouts",
        tag: "PROTOCOL",
        readTime: "9 min",
        title: "Space Protocol: Programming for Small Spaces",
        excerpt: "Smart periodisation and exercise selection when you have limited room to train.",
      },
      {
        id: "no_gym_required",
        slug: "no_gym_required",
        category: "Home Workouts",
        tag: "GUIDE",
        readTime: "5 min",
        title: "No Gym Required: The Case for Training at Home",
        excerpt: "Why removing the commute, cost, and crowds can actually improve your consistency.",
      },
    ],
  },

  "recovery_&_wellness": {
    featured: {
      id: "rest_&_adapt",
      slug: "rest_&_adapt",
      category: "Recovery & Wellness",
      tag: "SCIENCE",
      readTime: "9 min",
      title: "Rest and Adapt: Understanding the Adaptation Window",
      excerpt: "The physiology of recovery and how to optimise your training schedule around it.",
      image: "https://qvqrllepiterihelgckb.supabase.co/storage/v1/object/public/Assets/Articles/recovery_&_wellness/rest_and_adapt.webp",
    },
    posts: [
      {
        id: "recovery_protocol",
        slug: "recovery_protocol",
        category: "Recovery & Wellness",
        tag: "PROTOCOL",
        readTime: "8 min",
        title: "The Recovery Protocol: Sleep, Nutrition, and Active Rest",
        excerpt: "A structured system for recovering faster without doing less work.",
      },
      {
        id: "regenrate",
        slug: "regenrate",
        category: "Recovery & Wellness",
        tag: "WELLNESS",
        readTime: "6 min",
        title: "Regenrate: Regeneration Strategies for Hard Trainers",
        excerpt: "Advanced recovery modalities explained — what works, what is marketing, and what matters.",
      },
      {
        id: "wellness_core",
        slug: "wellness_core",
        category: "Recovery & Wellness",
        tag: "FOUNDATIONS",
        readTime: "5 min",
        title: "Wellness Core: The Non-Negotiables of Physical Health",
        excerpt: "Sleep, hydration, stress management — the foundations that every training plan rests on.",
      },
      {
        id: "rebuild",
        slug: "rebuild",
        category: "Recovery & Wellness",
        tag: "RECOVERY",
        readTime: "7 min",
        title: "Rebuild: The Art and Science of Supercompensation",
        excerpt: "Why what happens between your sessions matters as much as the sessions themselves.",
      },
    ],
  },
};